[package]
name = "control-plane-xtask"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["json"] }
control-plane-core = { path = "../control-plane-core" }
ess-conformance = { git = "https://github.com/beyond10x/ess", rev = "84ee8d38eb69e3a4507de801fdcb248232ed6e6e" }
ess-primitives = { git = "https://github.com/beyond10x/ess", rev = "84ee8d38eb69e3a4507de801fdcb248232ed6e6e" }
