[package]
name = "control-plane-xtask"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
control-plane-core = { path = "../control-plane-core" }
ess-conformance = { git = "https://github.com/beyond10x/ess", rev = "a81a8729dc252830d4e0557176522b59be6ff253" }
ess-primitives = { git = "https://github.com/beyond10x/ess", rev = "a81a8729dc252830d4e0557176522b59be6ff253" }
