//! Regenerate into a new ESS-owned directory, then compare or install emitter bytes.
use anyhow::{Context, Result, ensure};
use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    process::Command,
};

type Files = BTreeMap<PathBuf, Vec<u8>>;
fn refuse_symlink_ancestors(path: &Path) -> Result<()> {
    for ancestor in path.ancestors() {
        match fs::symlink_metadata(ancestor) {
            Ok(metadata) => ensure!(
                !metadata.file_type().is_symlink(),
                "generated symlink refused: {}",
                ancestor.display()
            ),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(error.into()),
        }
    }
    Ok(())
}

fn files(root: &Path) -> Result<Files> {
    refuse_symlink_ancestors(root)?;
    fn visit(root: &Path, dir: &Path, out: &mut Files) -> Result<()> {
        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            if entry.file_name() == ".ess-output" {
                continue;
            }
            let kind = entry.file_type()?;
            ensure!(
                !kind.is_symlink(),
                "generated symlink refused: {}",
                entry.path().display()
            );
            if kind.is_dir() {
                visit(root, &entry.path(), out)?;
            } else if kind.is_file() {
                out.insert(
                    entry.path().strip_prefix(root)?.to_owned(),
                    fs::read(entry.path())?,
                );
            }
        }
        Ok(())
    }
    let mut out = Files::new();
    visit(root, root, &mut out)?;
    Ok(out)
}

pub(crate) fn compare(expected: &Path, actual: &Path) -> Result<()> {
    let expected_files = files(expected)?;
    let actual_files = files(actual)?;
    ensure!(
        expected_files.keys().eq(actual_files.keys()),
        "generated file-set drift in {}",
        actual.display()
    );
    for (path, bytes) in expected_files {
        ensure!(
            actual_files[&path] == bytes,
            "generated byte drift: {}",
            actual.join(path).display()
        );
    }
    Ok(())
}

fn ess(root: &Path, args: &[&str]) -> Result<()> {
    let output = Command::new("ess")
        .current_dir(root)
        .args(args)
        .output()
        .context("start released ESS CLI")?;
    ensure!(
        output.status.success(),
        "ess {} failed:\n{}\n{}",
        args.join(" "),
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    print!("{}", String::from_utf8_lossy(&output.stdout));
    Ok(())
}

fn preflight(expected: &Path, actual: &Path) -> Result<()> {
    refuse_symlink_ancestors(actual)?;
    let new = files(expected)?;
    let old = if actual.exists() {
        files(actual)?
    } else {
        Files::new()
    };
    let extras = old
        .keys()
        .filter(|path| !new.contains_key(*path))
        .map(|path| actual.join(path).display().to_string())
        .collect::<Vec<_>>();
    ensure!(
        extras.is_empty(),
        "unowned or stale generated files require an explicit ownership decision before regeneration:\n{}",
        extras.join("\n")
    );
    for path in new.keys() {
        let destination = actual.join(path);
        ensure!(
            !destination.exists() || destination.is_file(),
            "generated file destination is occupied by a directory: {}",
            destination.display()
        );
    }
    Ok(())
}

fn install(expected: &Path, actual: &Path) -> Result<()> {
    preflight(expected, actual)?;
    let new = files(expected)?;
    fs::create_dir_all(actual)?;
    for (path, bytes) in new {
        let destination = actual.join(path);
        fs::create_dir_all(destination.parent().context("generated parent")?)?;
        fs::write(destination, bytes)?;
    }
    compare(expected, actual)
}

pub fn run(root: &Path, write: bool) -> Result<()> {
    refuse_symlink_ancestors(root)?;
    let scratch = root.join(".scratch");
    refuse_symlink_ancestors(&scratch)?;
    fs::create_dir_all(&scratch)?;
    let fresh = tempfile::Builder::new()
        .prefix("ess-generation-")
        .tempdir_in(scratch)?;
    let model = fresh.path().join("model");
    let api = fresh.path().join("api");
    let suite = fresh.path().join("conformance.json");
    ess(
        root,
        &["specify", "validate", "--path", "ess", "--strict-requires"],
    )?;
    ess(
        root,
        &[
            "generate",
            "synthesize",
            "--path",
            "ess",
            "--target",
            "rust",
            "--layout",
            "crate",
            "--out",
            model.to_str().context("model path UTF-8")?,
        ],
    )?;
    let plan: serde_json::Value = serde_json::from_slice(&fs::read(model.join("plan.json"))?)?;
    // ESS success permits obligations; this product requires entirely generated behavior.
    let capabilities = plan["capabilities"]
        .as_array()
        .context("generation plan capabilities")?;
    ensure!(
        !capabilities.is_empty()
            && capabilities
                .iter()
                .all(|c| c["disposition"]["disposition"] == "generated"),
        "generation left unmet capabilities"
    );
    ess(
        root,
        &[
            "generate",
            "--path",
            "ess",
            "--kind",
            "openapi",
            "--out",
            api.to_str().context("API path UTF-8")?,
        ],
    )?;
    ess(
        root,
        &[
            "verify",
            "conform",
            "synthesize",
            "--path",
            "ess",
            "--suite-format",
            "5",
            "--out",
            suite.to_str().context("suite path UTF-8")?,
        ],
    )?;
    let generated = root.join("generated");
    let destination = generated.join("conformance.json");
    // Preflight the entire output set before the first install. A refusal in API
    // output or the suite must leave even earlier model output byte-for-byte intact.
    if write {
        for (fresh, name) in [(&model, "model"), (&api, "api")] {
            preflight(fresh, &generated.join(name))?;
        }
        refuse_symlink_ancestors(&destination)?;
        ensure!(
            !destination.exists() || destination.is_file(),
            "conformance output is not a regular file"
        );
    }
    for (fresh, name) in [(&model, "model"), (&api, "api")] {
        if write {
            install(fresh, &generated.join(name))?;
        } else {
            compare(fresh, &generated.join(name))?;
        }
    }
    let bytes = fs::read(suite)?;
    if write {
        fs::write(&destination, &bytes)?;
    }
    ensure!(
        fs::read(destination)? == bytes,
        "generated byte drift: generated/conformance.json"
    );
    println!("generated contracts match emitter bytes");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn generated_contracts_do_not_drift() -> Result<()> {
        let dir = tempfile::tempdir()?;
        let expected = dir.path().join("expected");
        let actual = dir.path().join("actual");
        fs::create_dir_all(&expected)?;
        fs::create_dir_all(&actual)?;
        fs::write(expected.join("contract.rs"), "correct contract")?;
        fs::write(actual.join("contract.rs"), "incorrect contract")?;
        assert!(compare(&expected, &actual).is_err());
        install(&expected, &actual)?;
        fs::write(actual.join("stale.rs"), "obsolete")?;
        assert!(compare(&expected, &actual).is_err());
        assert!(install(&expected, &actual).is_err());
        assert_eq!(fs::read_to_string(actual.join("stale.rs"))?, "obsolete");
        // Removal is an explicit fixture ownership decision, never a generator effect.
        fs::remove_file(actual.join("stale.rs"))?;
        install(&expected, &actual)?;
        fs::create_dir_all(actual.join(".ess-output"))?;
        fs::write(actual.join(".ess-output/local.json"), "local ownership")?;
        compare(&expected, &actual)?;
        Ok(())
    }
}
