//! `frontend-check` runs the Vue component suite after the drift check and fails when it fails.
//!
//! The gate module is compiled in by path, so each case calls `frontend::run(root, false)`, which
//! is exactly what `frontend-check` runs; the binary's `main` returns that result, and Rust's
//! `Termination` turns an error into exit status 1. The binary bakes the repository root in at
//! build time, so it cannot be pointed at a fixture. Each case therefore copies `frontend/`
//! (without `node_modules`) into a temporary root under `TMPDIR` and links the installed
//! `frontend/node_modules` into it. The failing fixture is added to the copy only; the real
//! suite under `frontend/src` never contains it. Run `npm ci --prefix frontend` first.
#[allow(dead_code)]
#[path = "../src/frontend.rs"]
mod frontend;
#[allow(dead_code)]
#[path = "../src/generation.rs"]
mod generation;

use anyhow::{Context, Result, ensure};
use std::{
    fs,
    path::{Path, PathBuf},
    process::{ExitCode, Termination},
};

const FIXTURE: &str = include_str!("fixtures/frontend/failing.test.js");
const FIXTURE_TITLE: &str = "fixture component assertion that does not hold";

fn copy(from: &Path, to: &Path) -> Result<()> {
    fs::create_dir_all(to)?;
    for entry in fs::read_dir(from)? {
        let entry = entry?;
        let target = to.join(entry.file_name());
        let kind = entry.file_type()?;
        if entry.file_name() == "node_modules" {
            continue;
        } else if kind.is_dir() {
            copy(&entry.path(), &target)?;
        } else if kind.is_file() {
            fs::copy(entry.path(), target)?;
        }
    }
    Ok(())
}

/// A temporary repository root holding a copy of this tree's frontend and its installed packages.
/// The root is canonical: the drift check refuses a bundle path with a symlinked ancestor, which
/// a symlinked `TMPDIR` would otherwise supply.
fn frontend_copy() -> Result<(tempfile::TempDir, PathBuf)> {
    let source = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../frontend");
    let modules = fs::canonicalize(source.join("node_modules"))
        .context("frontend/node_modules is missing; run npm ci --prefix frontend first")?;
    let temporary = tempfile::Builder::new()
        .prefix("frontend-check-")
        .tempdir()?;
    let root = fs::canonicalize(temporary.path())?;
    copy(&source, &root.join("frontend"))?;
    std::os::unix::fs::symlink(modules, root.join("frontend/node_modules"))?;
    Ok((temporary, root))
}

fn exit_status(result: Result<()>) -> ExitCode {
    result.report()
}

#[test]
fn failing_component_test_fails_the_gate() -> Result<()> {
    let (_temporary, root) = frontend_copy()?;
    frontend::run(&root, false)
        .context("the unchanged frontend copy must pass, or the failure below proves nothing")?;

    fs::write(root.join("frontend/src/failing.test.js"), FIXTURE)?;
    let result = frontend::run(&root, false);
    let message = format!("{:#}", result.as_ref().err().context("gate passed")?);
    ensure!(
        message.contains("Vue component tests failed") && message.contains(FIXTURE_TITLE),
        "the gate must fail on the fixture component test, not on something else:\n{message}"
    );
    assert_eq!(exit_status(result), ExitCode::FAILURE);
    Ok(())
}

#[test]
fn component_tests_run_after_the_drift_check() -> Result<()> {
    let (_temporary, root) = frontend_copy()?;
    fs::write(root.join("frontend/src/failing.test.js"), FIXTURE)?;
    fs::write(root.join("frontend/dist/app.js"), "drifted bundle")?;
    let message = format!(
        "{:#}",
        frontend::run(&root, false).err().context("gate passed")?
    );
    ensure!(
        message.contains("generated byte drift") && !message.contains(FIXTURE_TITLE),
        "a drifted bundle must fail before the component suite runs:\n{message}"
    );
    Ok(())
}
