//! `frontend-check` runs the Vue component suite after the drift check and fails when it fails,
//! or when any test in it did not run.
//!
//! The gate module is compiled in by path, so each case calls `frontend::run(root, false)`, which
//! is exactly what `frontend-check` runs; the binary's `main` returns that result, and Rust's
//! `Termination` turns an error into exit status 1. The binary bakes the repository root in at
//! build time, so it cannot be pointed at a fixture. Each case therefore copies `frontend/`
//! (without `node_modules`) into a temporary root under `TMPDIR` and links the installed
//! packages into it. Fixtures are added to the copy only; the real suite under `frontend/src`
//! never contains them. Run `npm ci --prefix frontend` first.
#[allow(dead_code)]
#[path = "../src/frontend.rs"]
mod frontend;
#[allow(dead_code)]
#[path = "../src/generation.rs"]
mod generation;

use anyhow::{Context, Result, ensure};
use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    process::{ExitCode, Termination},
    time::SystemTime,
};

const FIXTURE: &str = include_str!("fixtures/frontend/failing.test.js");
const FIXTURE_TITLE: &str = "fixture component assertion that does not hold";

fn copy(from: &Path, to: &Path) -> Result<()> {
    fs::create_dir_all(to)?;
    for entry in fs::read_dir(from)? {
        let entry = entry?;
        let target = to.join(entry.file_name());
        let kind = entry.file_type()?;
        if entry.file_name() == "node_modules" {
            continue;
        } else if kind.is_dir() {
            copy(&entry.path(), &target)?;
        } else if kind.is_file() {
            fs::copy(entry.path(), target)?;
        }
    }
    Ok(())
}

/// A temporary repository root holding a copy of this tree's frontend and its installed packages.
/// The root is canonical: the drift check refuses a bundle path with a symlinked ancestor, which
/// a symlinked `TMPDIR` would otherwise supply.
///
/// `node_modules` in the copy is a real directory linking each installed package and `.bin`, so
/// Vite and Vitest write their caches (`.vite`, `.vite-temp`) into the copy. Other dot entries
/// are those caches and stay behind; linking the whole directory sent every write to the real one.
fn frontend_copy() -> Result<(tempfile::TempDir, PathBuf)> {
    let source = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../frontend");
    let modules = fs::canonicalize(source.join("node_modules"))
        .context("frontend/node_modules is missing; run npm ci --prefix frontend first")?;
    let temporary = tempfile::Builder::new()
        .prefix("frontend-check-")
        .tempdir()?;
    let root = fs::canonicalize(temporary.path())?;
    copy(&source, &root.join("frontend"))?;
    let linked = root.join("frontend/node_modules");
    fs::create_dir(&linked)?;
    for entry in fs::read_dir(&modules)? {
        let name = entry?.file_name();
        if name == ".bin" || !name.to_string_lossy().starts_with('.') {
            std::os::unix::fs::symlink(modules.join(&name), linked.join(&name))?;
        }
    }
    Ok((temporary, root))
}

fn exit_status(result: Result<()>) -> ExitCode {
    result.report()
}

#[test]
fn failing_component_test_fails_the_gate() -> Result<()> {
    let (_temporary, root) = frontend_copy()?;
    frontend::run(&root, false)
        .context("the unchanged frontend copy must pass, or the failure below proves nothing")?;

    fs::write(root.join("frontend/src/failing.test.js"), FIXTURE)?;
    let result = frontend::run(&root, false);
    let message = format!("{:#}", result.as_ref().err().context("gate passed")?);
    ensure!(
        message.contains("Vue component tests failed") && message.contains(FIXTURE_TITLE),
        "the gate must fail on the fixture component test, not on something else:\n{message}"
    );
    assert_eq!(exit_status(result), ExitCode::FAILURE);
    Ok(())
}

#[test]
fn component_tests_run_in_the_gate() -> Result<()> {
    let (_temporary, root) = frontend_copy()?;
    fs::write(root.join("frontend/src/failing.test.js"), FIXTURE)?;
    fs::write(root.join("frontend/dist/app.js"), "drifted bundle")?;
    let message = format!(
        "{:#}",
        frontend::run(&root, false).err().context("gate passed")?
    );
    ensure!(
        message.contains("generated byte drift") && !message.contains(FIXTURE_TITLE),
        "a drifted bundle must fail before the component suite runs:\n{message}"
    );
    Ok(())
}

const UNRUN: &str = include_str!("fixtures/frontend/unrun.test.js");
const UNRUN_TITLES: [&str; 11] = [
    "fixture skipped suite (skipped)",
    "fixture skipped suite > fixture test in a skipped suite (skipped)",
    "fixture empty skipped suite (skipped)",
    "fixture todo suite (todo)",
    "fixture skipped test (skipped)",
    "fixture skipIf test (skipped)",
    "fixture todo test (todo)",
    "fixture test that skips itself (skipped)",
    "fixture expected-fail test (expected fail)",
    "fixture expected-fail option (expected fail)",
    "fixture aliased expected-fail test (expected fail)",
];

#[test]
fn unrun_component_tests_fail_the_gate_by_name() -> Result<()> {
    let (_temporary, root) = frontend_copy()?;
    fs::write(root.join("frontend/src/unrun.test.js"), UNRUN)?;
    let message = format!(
        "{:#}",
        frontend::run(&root, false).err().context("gate passed")?
    );
    let unnamed: Vec<_> = UNRUN_TITLES
        .into_iter()
        .filter(|title| !message.contains(&format!("src/unrun.test.js > {title}")))
        .collect();
    ensure!(
        message.contains("Vue component tests failed") && unnamed.is_empty(),
        "the gate must refuse every test that did not run and name it; unnamed: {unnamed:?}\n{message}"
    );
    Ok(())
}

/// One failing file per axis of Vitest's default pattern `**/*.{test,spec}.?(c|m)[jt]s?(x)`,
/// plus one outside `src/`; the gate must run, and fail on, every one of them.
const CONVENTIONAL: [&str; 6] = [
    "src/planted.spec.js",
    "src/planted.test.ts",
    "src/planted.test.mjs",
    "src/planted.spec.jsx",
    "src/planted.test.tsx",
    "tests/unit/planted.test.js",
];

#[test]
fn every_conventional_test_file_runs_in_the_gate() -> Result<()> {
    let (_temporary, root) = frontend_copy()?;
    for file in CONVENTIONAL {
        let path = root.join("frontend").join(file);
        fs::create_dir_all(path.parent().context("planted file has a parent")?)?;
        fs::write(
            path,
            format!(
                "import {{ expect, test }} from 'vitest'\ntest('planted failure in {file}', () => {{ expect('ran').toBe('never') }})\n"
            ),
        )?;
    }
    let message = format!(
        "{:#}",
        frontend::run(&root, false).err().context("gate passed")?
    );
    let skipped: Vec<_> = CONVENTIONAL
        .into_iter()
        .filter(|file| !message.contains(&format!("planted failure in {file}")))
        .collect();
    ensure!(
        message.contains("Vue component tests failed") && skipped.is_empty(),
        "the gate must run every file Vitest's default pattern names; not run: {skipped:?}\n{message}"
    );
    Ok(())
}

/// `dangerouslyIgnoreUnhandledErrors` makes Vitest exit 0 after an unhandled rejection; the gate
/// must still refuse the run and name the error.
#[test]
fn unhandled_errors_fail_the_gate() -> Result<()> {
    let (_temporary, root) = frontend_copy()?;
    let config = root.join("frontend/vitest.config.js");
    let text = fs::read_to_string(&config)?;
    ensure!(
        text.contains("allowOnly: false"),
        "vitest.config.js no longer sets allowOnly"
    );
    fs::write(
        &config,
        text.replacen(
            "allowOnly: false",
            "allowOnly: false, dangerouslyIgnoreUnhandledErrors: true",
            1,
        ),
    )?;
    fs::write(
        root.join("frontend/src/unhandled.test.js"),
        "import { test } from 'vitest'\ntest('fixture test leaving an unhandled rejection', () => { Promise.reject(new Error('fixture unhandled rejection')) })\n",
    )?;
    let message = format!(
        "{:#}",
        frontend::run(&root, false).err().context("gate passed")?
    );
    ensure!(
        message.contains("Vue component tests failed")
            && message.contains("unhandled error (fixture unhandled rejection)"),
        "the gate must refuse a run with an unhandled error and name it:\n{message}"
    );
    Ok(())
}

/// Path, size and modification time of every entry under `dir`, symlinks not followed.
fn tree_state(dir: &Path, state: &mut BTreeMap<PathBuf, (u64, SystemTime)>) -> Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let metadata = entry.metadata()?;
        state.insert(entry.path(), (metadata.len(), metadata.modified()?));
        if metadata.is_dir() {
            tree_state(&entry.path(), state)?;
        }
    }
    Ok(())
}

#[test]
fn component_tests_leave_the_real_frontend_untouched() -> Result<()> {
    let real = fs::canonicalize(Path::new(env!("CARGO_MANIFEST_DIR")).join("../../frontend"))?;
    let mut before = BTreeMap::new();
    tree_state(&real, &mut before)?;
    let (_temporary, root) = frontend_copy()?;
    fs::write(root.join("frontend/src/failing.test.js"), FIXTURE)?;
    ensure!(
        frontend::run(&root, false).is_err(),
        "the fixture must fail the copy"
    );
    let mut after = BTreeMap::new();
    tree_state(&real, &mut after)?;
    let written: Vec<_> = before
        .keys()
        .chain(after.keys())
        .filter(|path| before.get(*path) != after.get(*path))
        .map(|path| {
            path.strip_prefix(&real)
                .unwrap_or(path)
                .display()
                .to_string()
        })
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();
    ensure!(
        written.is_empty(),
        "a gate run on a copy wrote into the real frontend/: {written:?}"
    );
    Ok(())
}
